# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Joey lee
email: lmqnet@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web Developer, Sport
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lmqnet.github.io" # the base hostname & protocol for your site
twitter_username: lmqnet
github_username:  lmqnet

# Build settings
markdown: kramdown
